_b = 1674
_c = 0
_d = _b >> 2
_e = _b >> 3
_f = _b >> 5
_g = _e | _f
_h = _e & _f
_i = ~_h
_j = _g & _i
_k = _d | _j
_l = _d & _j
_m = ~_l
_n = _k & _m
_o = _b | _n
_p = _b & _n
_q = ~_p
_r = _o & _q
_s = 1 & _r
_t = _c << 1
_u = _t | _s
_v = _b >> 1
_w = _s << 15
_x = _v | _w
_y = _x >> 2
_z = _x >> 3
_aa = _x >> 5
_ab = _z | _aa
_ac = _z & _aa
_ad = ~_ac
_ae = _ab & _ad
_af = _y | _ae
_ag = _y & _ae
_ah = ~_ag
_ai = _af & _ah
_aj = _x | _ai
_ak = _x & _ai
_al = ~_ak
_am = _aj & _al
_an = 1 & _am
_ao = _u << 1
_ap = _ao | _an
_aq = _x >> 1
_ar = _an << 15
_as = _aq | _ar
_at = _as >> 2
_au = _as >> 3
_av = _as >> 5
_aw = _au | _av
_ax = _au & _av
_ay = ~_ax
_az = _aw & _ay
_ba = _at | _az
_bb = _at & _az
_bc = ~_bb
_bd = _ba & _bc
_be = _as | _bd
_bf = _as & _bd
_bg = ~_bf
_bh = _be & _bg
_bi = 1 & _bh
_bj = _ap << 1
_bk = _bj | _bi
_bl = _as >> 1
_bm = _bi << 15
_bn = _bl | _bm
_bo = _bn >> 2
_bp = _bn >> 3
_bq = _bn >> 5
_br = _bp | _bq
_bs = _bp & _bq
_bt = ~_bs
_bu = _br & _bt
_bv = _bo | _bu
_bw = _bo & _bu
_bx = ~_bw
_by = _bv & _bx
_bz = _bn | _by
_ca = _bn & _by
_cb = ~_ca
_cc = _bz & _cb
_cd = 1 & _cc
_ce = _bk << 1
_cf = _ce | _cd
_cg = _bn >> 1
_ch = _cd << 15
_ci = _cg | _ch
_cj = _ci >> 2
_ck = _ci >> 3
_cl = _ci >> 5
_cm = _ck | _cl
_cn = _ck & _cl
_co = ~_cn
_cp = _cm & _co
_cq = _cj | _cp
_cr = _cj & _cp
_cs = ~_cr
_ct = _cq & _cs
_cu = _ci | _ct
_cv = _ci & _ct
_cw = ~_cv
_cx = _cu & _cw
_cy = 1 & _cx
_cz = _cf << 1
_da = _cz | _cy
_db = _ci >> 1
_dc = _cy << 15
_dd = _db | _dc
_de = _dd >> 2
_df = _dd >> 3
_dg = _dd >> 5
_dh = _df | _dg
_di = _df & _dg
_dj = ~_di
_dk = _dh & _dj
_dl = _de | _dk
_dm = _de & _dk
_dn = ~_dm
_do = _dl & _dn
_dp = _dd | _do
_dq = _dd & _do
_dr = ~_dq
_ds = _dp & _dr
_dt = 1 & _ds
_du = _da << 1
_dv = _du | _dt
_dw = _dd >> 1
_dx = _dt << 15
_dy = _dw | _dx
_dz = _dy >> 2
_ea = _dy >> 3
_eb = _dy >> 5
_ec = _ea | _eb
_ed = _ea & _eb
_ee = ~_ed
_ef = _ec & _ee
_eg = _dz | _ef
_eh = _dz & _ef
_ei = ~_eh
_ej = _eg & _ei
_ek = _dy | _ej
_el = _dy & _ej
_em = ~_el
_en = _ek & _em
_eo = 1 & _en
_ep = _dv << 1
_eq = _ep | _eo
_er = _dy >> 1
_es = _eo << 15
_et = _er | _es
_eu = _et >> 2
_ev = _et >> 3
_ew = _et >> 5
_ex = _ev | _ew
_ey = _ev & _ew
_ez = ~_ey
_fa = _ex & _ez
_fb = _eu | _fa
_fc = _eu & _fa
_fd = ~_fc
_fe = _fb & _fd
_ff = _et | _fe
_fg = _et & _fe
_fh = ~_fg
_fi = _ff & _fh
_fj = 1 & _fi
_fk = _eq << 1
_fl = _fk | _fj
_fm = _et >> 1
_fn = _fj << 15
_fo = _fm | _fn
_fp = _fo >> 2
_fq = _fo >> 3
_fr = _fo >> 5
_fs = _fq | _fr
_ft = _fq & _fr
_fu = ~_ft
_fv = _fs & _fu
_fw = _fp | _fv
_fx = _fp & _fv
_fy = ~_fx
_fz = _fw & _fy
_ga = _fo | _fz
_gb = _fo & _fz
_gc = ~_gb
_gd = _ga & _gc
_ge = 1 & _gd
_gf = _fl << 1
_gg = _gf | _ge
_gh = _fo >> 1
_gi = _ge << 15
_gj = _gh | _gi
_gk = _gj >> 2
_gl = _gj >> 3
_gm = _gj >> 5
_gn = _gl | _gm
_go = _gl & _gm
_gp = ~_go
_gq = _gn & _gp
_gr = _gk | _gq
_gs = _gk & _gq
_gt = ~_gs
_gu = _gr & _gt
_gv = _gj | _gu
_gw = _gj & _gu
_gx = ~_gw
_gy = _gv & _gx
_gz = 1 & _gy
_ha = _gg << 1
_hb = _ha | _gz
_hc = _gj >> 1
_hd = _gz << 15
_he = _hc | _hd
_hf = _he >> 2
_hg = _he >> 3
_hh = _he >> 5
_hi = _hg | _hh
_hj = _hg & _hh
_hk = ~_hj
_hl = _hi & _hk
_hm = _hf | _hl
_hn = _hf & _hl
_ho = ~_hn
_hp = _hm & _ho
_hq = _he | _hp
_hr = _he & _hp
_hs = ~_hr
_ht = _hq & _hs
_hu = 1 & _ht
_hv = _hb << 1
_hw = _hv | _hu
_hx = _he >> 1
_hy = _hu << 15
_hz = _hx | _hy
_ia = _hz >> 2
_ib = _hz >> 3
_ic = _hz >> 5
_id = _ib | _ic
_ie = _ib & _ic
_if = ~_ie
_ig = _id & _if
_ih = _ia | _ig
_ii = _ia & _ig
_ij = ~_ii
_ik = _ih & _ij
_il = _hz | _ik
_im = _hz & _ik
_in = ~_im
_io = _il & _in
_ip = 1 & _io
_iq = _hw << 1
_ir = _iq | _ip
_is = _hz >> 1
_it = _ip << 15
_iu = _is | _it
_iv = _iu >> 2
_iw = _iu >> 3
_ix = _iu >> 5
_iy = _iw | _ix
_iz = _iw & _ix
_ja = ~_iz
_jb = _iy & _ja
_jc = _iv | _jb
_jd = _iv & _jb
_je = ~_jd
_jf = _jc & _je
_jg = _iu | _jf
_jh = _iu & _jf
_ji = ~_jh
_jj = _jg & _ji
_jk = 1 & _jj
_jl = _ir << 1
_jm = _jl | _jk
_jn = _iu >> 1
_jo = _jk << 15
_jp = _jn | _jo
_jq = _jp >> 2
_jr = _jp >> 3
_js = _jp >> 5
_jt = _jr | _js
_ju = _jr & _js
_jv = ~_ju
_jw = _jt & _jv
_jx = _jq | _jw
_jy = _jq & _jw
_jz = ~_jy
_ka = _jx & _jz
_kb = _jp | _ka
_kc = _jp & _ka
_kd = ~_kc
_ke = _kb & _kd
_kf = 1 & _ke
_kg = _jm << 1
_kh = _kg | _kf
_ki = _jp >> 1
_kj = _kf << 15
_kk = _ki | _kj
_kl = _kk >> 2
_km = _kk >> 3
_kn = _kk >> 5
_ko = _km | _kn
_kp = _km & _kn
_kq = ~_kp
_kr = _ko & _kq
_ks = _kl | _kr
_kt = _kl & _kr
_ku = ~_kt
_kv = _ks & _ku
_kw = _kk | _kv
_kx = _kk & _kv
_ky = ~_kx
_kz = _kw & _ky
_la = 1 & _kz
_lb = _kh << 1
_lc = _lb | _la
_ld = _kk >> 1
_le = _la << 15
_lf = _ld | _le
_lg = _lf >> 2
_lh = _lf >> 3
_li = _lf >> 5
_lj = _lh | _li
_lk = _lh & _li
_ll = ~_lk
_lm = _lj & _ll
_ln = _lg | _lm
_lo = _lg & _lm
_lp = ~_lo
_lq = _ln & _lp
_lr = _lf | _lq
_ls = _lf & _lq
_lt = ~_ls
_lu = _lr & _lt
_lv = 1 & _lu
_lw = _lc << 1
_lx = _lw | _lv
_ly = _lf >> 1
_lz = _lv << 15
_ma = _ly | _lz
_a = _lx
puts _a